// Generated by CoffeeScript 1.12.4
(function() {
  var assets, browserSync, concat, del, fs, gulp, minifyCss, runSequence, uglify;

  gulp = require('gulp');

  del = require('del');

  fs = require('fs');

  runSequence = require('run-sequence');

  uglify = require('gulp-uglify');

  minifyCss = require('gulp-minify-css');

  concat = require('gulp-concat');

  browserSync = require('browser-sync');

  assets = JSON.parse(fs.readFileSync("assets.json"));

  gulp.task('default', function(callback) {
    return runSequence(['clean'], ['build'], ['server'], ['watch'], callback);
  });

  gulp.task('clean', function(callback) {
    return del(['./dist'], callback);
  });

  gulp.task('build', function(callback) {
    return runSequence(['assetsJs', 'assetsCss', 'assetsFont'], ['appJs', 'appCss', 'copyHtml', 'copyConfig'], callback);
  });

  gulp.task('assetsJs', function() {
    return gulp.src(assets.assetsJs).pipe(concat('assets.js', {
      newLine: '\n\n'
    })).pipe(gulp.dest('./dist/assets/js/'));
  });

  gulp.task('assetsCss', function() {
    return gulp.src(assets.assetsCss).pipe(concat('assets.css', {
      newLine: '\n\n'
    })).pipe(gulp.dest('./dist/assets/css/'));
  });

  gulp.task('assetsFont', function() {
    return gulp.src(assets.assetsFont).pipe(gulp.dest('./dist/assets/fonts/'));
  });

  gulp.task('appJs', function() {
    return gulp.src(assets.appJs).pipe(concat('app.js', {
      newLine: ';\n'
    })).pipe(gulp.dest('./dist/assets/js'));
  });

  gulp.task('appCss', function() {
    return gulp.src(assets.appCss).pipe(concat('app.css', {
      newLine: '\n\n'
    })).pipe(gulp.dest('./dist/assets/css'));
  });

  gulp.task('copyHtml', function() {
    return gulp.src(['./src/**/*.html']).pipe(gulp.dest('./dist/'));
  });

  gulp.task('copyConfig', function() {
    return gulp.src(['./src/config/**/*.js']).pipe(gulp.dest('./dist/config/'));
  });

  gulp.task('server', function() {
    return browserSync.init({
      server: {
        baseDir: './dist/'
      },
      port: 3005
    });
  });

  gulp.task('watch', function() {
    return gulp.watch('./src/**/*.*', ['reload']);
  });

  gulp.task('reload', function(callback) {
    return runSequence(['build'], ['reload-browser'], callback);
  });

  gulp.task('reload-browser', function() {
    return browserSync.reload();
  });

}).call(this);

//# sourceMappingURL=gulpfile.js.map
