// Generated by CoffeeScript 1.12.4

/*
  这是多行注释
 */

(function() {
  var a, aaa, arr, f1, f2, i, isRight, len, num, obj, result, str;

  a = 10;

  str = 'abc';

  console.log("变量a=" + a);

  isRight = true;

  obj = {
    name: 'tom',
    age: 19
  };

  aaa = 18;

  f1 = function(num1, num2) {
    num1 += 4;
    console.log(num1);
    return num1 + num2;
  };

  result = f1(10, 20);

  console.log(result);

  f2 = function(num1, num2) {
    if (num2 == null) {
      num2 = 20;
    }
    return console.log(num1 + num2);
  };

  f2(30);

  f2(30, 10);

  if (obj.age > 18) {
    console.log(obj.name);
  }

  if (obj.age > 18) {
    console.log(obj.name);
  }

  if (!(obj.age > 18)) {
    console.log(obj.name);
  }

  if (obj.age > 18) {
    console.log(obj.name);
  }

  if (obj.name === 'tom') {
    obj.pwd = '123';
    console.log('用户名对');
  } else if (obj.name === 'jack') {
    obj.pwd = 'abc';
    console.log('系统用户');
    if (obj.age > 20) {
      console.log('已成人');
    }
  }

  arr = [1, 2, 3, 4, 5];

  for (i = 0, len = arr.length; i < len; i++) {
    num = arr[i];
    if (num % 2 === 0) {
      console.log(num + '是偶数');
    } else {
      console.log(num + "是奇数");
    }
  }

}).call(this);

//# sourceMappingURL=test.js.map
