// Generated by CoffeeScript 1.12.4
(function() {
  var app, bodyParser, cors, express, index, logger, path, taskRouter, userRouter;

  express = require('express');

  path = require('path');

  logger = require('morgan');

  bodyParser = require('body-parser');

  index = require('./../routes/index');

  userRouter = require('./../routes/user');

  taskRouter = require('./../routes/task');

  cors = require('cors');

  app = express();

  app.use(logger('dev'));

  app.use(bodyParser.json());

  app.use(bodyParser.urlencoded({
    extended: false
  }));

  app.use(cors());

  app.use('/api', index);

  app.use('/api', userRouter);

  app.use('/api', taskRouter);

  app.use(function(req, res, next) {
    var err;
    err = new Error('Not Found');
    err.status = 404;
    return next(err);
  });

  app.use(function(err, req, res, next) {
    return res.send(err.status || 500, {
      message: err.message
    });
  });

  module.exports = app;

}).call(this);

//# sourceMappingURL=app.js.map
