// Generated by CoffeeScript 1.12.4
(function() {
  var path;

  path = require('path');

  module.exports = {
    port: 3010,
    dbFilePath: path.join(__dirname, './../../database/')
  };

}).call(this);

//# sourceMappingURL=config.js.map
