// Generated by CoffeeScript 1.12.4
(function() {
  var del, developServer, gulp, notify, runSequence;

  gulp = require('gulp');

  del = require('del');

  developServer = require('gulp-develop-server');

  runSequence = require('run-sequence');

  notify = require('gulp-notify');

  gulp.task('default', function(callback) {
    return runSequence(['clean'], ['copy'], ['server'], ['watch'], callback);
  });

  gulp.task('clean', function(callback) {
    return del('./dist/', callback);
  });

  gulp.task('copy', function() {
    return gulp.src('./src/**/*.js').pipe(gulp.dest('./dist/'));
  });

  gulp.task('server', function() {
    return developServer.listen({
      path: './dist/www.js'
    });
  });

  gulp.task('watch', function() {
    return gulp.watch('./src/**/*.js', ['reload']);
  });

  gulp.task('reload', function(callback) {
    return runSequence(['copy'], ['reload-node'], callback);
  });

  gulp.task('reload-node', function() {
    developServer.restart();
    return gulp.src('./dist/www.js').pipe(notify('服务器已重启'));
  });

}).call(this);

//# sourceMappingURL=gulpfile.js.map
