// Generated by CoffeeScript 1.12.4
(function() {
  angular.module('myApp').controller('IndexCtrl', [
    '$scope', '$location', '$http', 'tmsUtils', function($scope, $location, $http, tmsUtils) {
      var init;
      console.log('这是首页控制器');
      $scope.task = {
        description: ''
      };
      $scope.taskList = [];
      $scope.exit = function() {
        console.log("退出登录");
        return $http.post(Tms.apiAddr + "/api/user/logout").then(function() {
          alert('用户已注销');
          return $location.path("/login");
        }, tmsUtils.processHttpError);
      };
      init = function() {
        $http.get(Tms.apiAddr + "/api/task").then(function(res) {
          var tasks;
          tasks = res.data;
          return $scope.taskList = tasks;
        }, tmsUtils.processHttpError);
      };
      init();
      $scope.addTask = function() {
        var task;
        task = angular.copy($scope.task);
        task.checked = false;
        return $http.post(Tms.apiAddr + "/api/task", task).then(function(res) {
          var newTask;
          newTask = res.data;
          task._id = newTask._id;
          task.deleted = newTask.deleted;
          $scope.taskList.push(task);
          return $scope.task.description = '';
        }, tmsUtils.processHttpError);
      };
      $scope.changeTaskStatus = function(task) {
        return task.status = task.checked ? 'Finish' : 'InProgress';
      };
      $scope.editTask = function(task) {
        task.isEditing = true;
        return task.tempDescription = task.description;
      };
      $scope.cancelEditTask = function(task) {
        return task.isEditing = false;
      };
      $scope.saveTask = function(task) {
        var oldDescription;
        console.log('保存编辑');
        oldDescription = task.description;
        task.description = task.tempDescription;
        return $http.put(Tms.apiAddr + "/api/task", task).then(function(res) {
          return task.isEditing = false;
        }, function(res) {
          task.description = oldDescription;
          return tmsUtils.processHttpError(res);
        });
      };
      $scope.deleteTask = function(task, index) {
        task.deleted = true;
        return $http.put(Tms.apiAddr + "/api/task", task).then(function(res) {
          return $scope.taskList.splice(index, 1);
        }, tmsUtils.processHttpError);
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=indexCtrl.js.map
